---

  - name: Install Docker
    shell: |
      apt-get update
      apt-get install docker.io -y
      
  - name: Install minikube
    shell: |      
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube
      cp minikube /usr/local/bin && rm minikube
      
  - name: Install kubectl
    shell: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl