---

  - name: copy
    become: yes
    copy:
      src: newgrp.sh
      dest: /home/ubuntu/newgrp.sh
      
  - name: Install minikube
    shell: |      
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube
      cp minikube /usr/local/bin && rm minikube
      
  - name: Install kubectl
    shell: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      
  - name: Install Docker
    shell: |
      apt-get update
      apt-get install docker.io -y
      
  - name: add user to docker group
    ansible.builtin.user:
      name: ubuntu
      groups: docker
      append: yes
      
  #- name: lauch newgrp
    #shell: |
      #sudo chmod +x newgrp.sh
      #./newgrp.sh
  
  - name: reset ssh connection to allow user changes to affect ansible user
    ansible.builtin.meta:
      reset_connection