---

- name: "deploy"
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "for target connection."
      wait_for_connection:
        timeout: 60

  roles:
    - deploy