apiVersion: apps/v1
kind: Deployment
metadata:
  name: posio
  labels:
    app: posio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posio
  template:
    metadata:
      labels:
        app: posio
    spec:
      containers:
      - name: posio
        image: fnim987/posio:v1.1.1
        ports:
        - containerPort: 5000